//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dominio.Modelo.Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cliente
    {
        public int id_cliente { get; set; }
        public string nombre { get; set; }
        public string apellido { get; set; }
        public string direccion { get; set; }
        public string telefono { get; set; }
        public string email { get; set; }
        public string foto { get; set; }
        public Nullable<decimal> altura { get; set; }
        public Nullable<decimal> peso { get; set; }
        public bool estado { get; set; }
        public Nullable<int> id_promocion_membresia { get; set; }
    
        public virtual Promociones_membresias Promociones_membresias { get; set; }
    }
}
