//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dominio.Modelo.Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cliente
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Cliente()
        {
            this.Registro_Asistencia = new HashSet<Registro_Asistencia>();
        }
    
        public int id_cliente { get; set; }
        public string cedula { get; set; }
        public string nombre { get; set; }
        public string apellido { get; set; }
        public string direccion { get; set; }
        public string telefono { get; set; }
        public string email { get; set; }
        public byte[] foto { get; set; }
        public Nullable<decimal> altura { get; set; }
        public Nullable<decimal> peso { get; set; }
        public bool estado { get; set; }
        public Nullable<int> id_membresia { get; set; }
        public Nullable<int> id_tipo_cliente { get; set; }
        public Nullable<System.DateTime> fecha_nacimiento { get; set; }
    
        public virtual Membresias Membresias { get; set; }
        public virtual Tipo_Cliente Tipo_Cliente { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Registro_Asistencia> Registro_Asistencia { get; set; }
    }
}
