//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dominio.Modelo.Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class Costo_Membresia
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Costo_Membresia()
        {
            this.Membresias = new HashSet<Membresias>();
        }
    
        public int id_costo_membresia { get; set; }
        public string descripcion { get; set; }
        public Nullable<decimal> valor { get; set; }
        public bool estado { get; set; }
        public Nullable<int> id_tipo_membresia { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Membresias> Membresias { get; set; }
        public virtual Tipo_Membresia Tipo_Membresia { get; set; }
    }
}
