//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dominio.Modelo.Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pago_diario
    {
        public int id_pago_diario { get; set; }
        public System.DateTime fecha { get; set; }
        public decimal monto { get; set; }
        public bool estado { get; set; }
        public Nullable<int> id_registro { get; set; }
    
        public virtual Registro_Asistencia Registro_Asistencia { get; set; }
    }
}
