//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Infraestructura.AccesoDatos
{
    using Dominio.Modelo.Entidades;
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class gestion_membresiasEntities : DbContext
    {
        public gestion_membresiasEntities()
            : base("name=gestion_membresiasEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Cliente> Cliente { get; set; }
        public virtual DbSet<Costo_Membresia> Costo_Membresia { get; set; }
        public virtual DbSet<Membresias> Membresias { get; set; }
        public virtual DbSet<Pago_diario> Pago_diario { get; set; }
        public virtual DbSet<Promociones> Promociones { get; set; }
        public virtual DbSet<Registro_Asistencia> Registro_Asistencia { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<Tipo_Cliente> Tipo_Cliente { get; set; }
        public virtual DbSet<Tipo_Membresia> Tipo_Membresia { get; set; }
        public virtual DbSet<Usuario> Usuario { get; set; }
    }
}
